events/urls.py
from django.urls import path
from . import views
from django.views.decorators.http import require_POST


app_name = 'events'

urlpatterns = [
    path('list/', views.EventListView.as_view(), name='event_list'),
    path('detail/<int:pk>/', views.EventDetailView.as_view(), name='event_detail'),

    path('event-create/', views.EventCreateView.as_view(), name='event_create'),
    path('event-update/<int:pk>/', views.EventUpdateView.as_view(), name='event_update'),
    path('event-enroll/', require_POST(views.EventEnrollView.as_view()), name='event_enroll'),
    path('event-delete/<int:pk>/', views.EventDeleteView.as_view(), name='event_delete'),
]

realworlddjango/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]


if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Backend URLs
urlpatterns += [
    path('events/', include('events.urls'))
]

# API URLs
urlpatterns += [
    path('api/events/', include('events.urls_api')),
]

events/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from django.urls import reverse
# from django.utils.text import slugify
# from unidecode import unidecode


class Category(models.Model):
    title = models.CharField(max_length=90, default='', verbose_name='Название')

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.title

    def display_event_count(self):
        return self.events.count()


class Feature(models.Model):
    title = models.CharField(max_length=200, default='', verbose_name='Название')

    class Meta:
        verbose_name = 'Свойство события'
        verbose_name_plural = 'Свойства события'

    def __str__(self):
        return self.title


class Event(models.Model):
    FULLNESS_FREE = '0'
    FULLNESS_MIDDLE = '1'
    FULLNESS_FULL = '2'

    FULLNESS_LEGEND_FREE = '<= 50%'
    FULLNESS_LEGEND_MIDDLE = '> 50%'
    FULLNESS_LEGEND_FULL = 'sold-out'

    FULLNESS_VARIANTS = (
        (FULLNESS_FREE, FULLNESS_LEGEND_FREE),
        (FULLNESS_MIDDLE, FULLNESS_LEGEND_MIDDLE),
        (FULLNESS_FULL, FULLNESS_LEGEND_FULL),
    )

    title = models.CharField(max_length=200, default='', verbose_name='Название')
    description = models.TextField(default='', verbose_name='Описание')
    date_start = models.DateTimeField(verbose_name='Дата начала')
    participants_number = models.PositiveSmallIntegerField(verbose_name='Количество участников')
    is_private = models.BooleanField(default=False, verbose_name='Частное')
    category = models.ForeignKey(Category, null=True, on_delete=models.CASCADE, related_name='events')
    features = models.ManyToManyField(Feature, related_name='events')
    logo = models.ImageField(upload_to='events/event', blank=True, null=True)

    class Meta:
        verbose_name = 'Событие'
        verbose_name_plural = 'События'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('events:event_detail', args=[str(self.pk)])

    def display_enroll_count(self):
        return self.enrolls.count()

    display_enroll_count.short_description = 'Количество записей'

    def display_places_left(self):
        places_left = self.participants_number - self.enrolls.count()
        if places_left == 0:
            fullness = self.FULLNESS_LEGEND_FULL
        elif self.enrolls.count() >= places_left:
            fullness = self.FULLNESS_LEGEND_MIDDLE
        else:
            fullness = self.FULLNESS_FREE
        return f'{places_left} ({fullness})'

    display_places_left.short_description = 'Осталось мест'

    @ property
    def rate(self):
        queryset_rates = self.reviews.select_related('user').values_list('rate', flat=True)
        queryset_rates_count = queryset_rates.count()
        if queryset_rates_count == 0:
            rates = 0
        else:
            rates = sum(queryset_rates) / queryset_rates_count
        return round(rates, 1)

    @property
    def logo_url(self):
        return self.logo.url if self.logo else f'{settings.STATIC_URL}images/svg-icon/event.svg'

    def get_update_url(self):
        return reverse('events:event_update', args=[str(self.pk)])

    def get_delete_url(self):
        return reverse('events:event_delete', args=[str(self.pk)])


class Enroll(models.Model):
    user = models.ForeignKey(User, null=True, on_delete=models.CASCADE, related_name='enrolls')
    event = models.ForeignKey(Event, null=True, on_delete=models.CASCADE, related_name='enrolls')
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Запись на событие'
        verbose_name_plural = 'Записи на событие'


class Review(models.Model):
    user = models.ForeignKey(User, null=True, on_delete=models.CASCADE, related_name='reviews')
    event = models.ForeignKey(Event, null=True, on_delete=models.CASCADE, related_name='reviews')
    rate = models.PositiveSmallIntegerField(null=True, verbose_name='оценка пользователя')
    text = models.TextField(max_length=1000, default='', blank=True, verbose_name='текст отзыва')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Отзыв на событие'
        verbose_name_plural = 'Отзывы на событие'

events/forms.py
from django import forms
from events.models import Event, Enroll


class EventUpdateForm(forms.ModelForm):
    date_start = forms.DateTimeField(label='Дата начала',
                                     widget=forms.DateTimeInput(format="%Y-%m-%dT%H:%M",
                                                                attrs={'type': 'datetime-local'})
                                     )

    class Meta:
        model = Event
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['date_start'].widget.attrs.update({'class': 'form-control'})


class EventCreateForm(EventUpdateForm):
    def clean(self):
        cleaned_data = super().clean()

        if Event.objects.filter(title=cleaned_data.get('title')).exists():
            raise forms.ValidationError(f'Событие уже существует')

        return cleaned_data


class EventEnrollForm(forms.ModelForm):
    class Meta:
        model = Enroll
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget = forms.HiddenInput()

    def clean(self):
        cleaned_data = super().clean()

        if Enroll.objects.filter(user=cleaned_data.get('user'), event=cleaned_data.get('event')).exists():
            raise forms.ValidationError(f'Вы уже записаны на это событие')

        return cleaned_data

events/views.py
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist
from django.views.decorators.http import require_POST
from django.views.generic import ListView, UpdateView, DetailView, TemplateView, CreateView, DeleteView
from django.views.generic.edit import ProcessFormView
from django.http import JsonResponse, HttpResponseForbidden, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy

from events.models import Event, Review, Category, Feature, Enroll
import datetime
from events.forms import EventUpdateForm, EventEnrollForm, EventCreateForm


class EventListView(ListView):
    model = Event
    template_name = 'events/event_list.html'
    paginate_by = 9

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['event_objects'] = Event.objects.all()
        context['category_objects'] = Category.objects.all()
        context['feature_objects'] = Feature.objects.all()
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.order_by('-pk')


class LoginRequiredMixin:
    def get(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return HttpResponseForbidden('Недостаточно прав')
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return HttpResponseForbidden('Недостаточно прав')
        return super().post(request, *args, **kwargs)


class EventDetailView(DetailView):
    model = Event
    template_name = 'events/event_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        event = self.object

        places_left = event.participants_number - event.enrolls.count()
        try:
            fullness_percent = int(event.enrolls.count() * 100 / event.participants_number)
        except ZeroDivisionError:
            fullness_percent = 0

        context['event'] = event
        context['places_left'] = places_left
        context['fullness_percent'] = fullness_percent
        return context


class EventCreateView(LoginRequiredMixin, CreateView):
    model = Event
    form_class = EventCreateForm
    template_name = 'events/event_update.html'

    success_url = reverse_lazy('events:event_list')

    def form_valid(self, form):
        messages.success(self.request, 'Новое событие создано успешно')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, form.non_field_errors())
        return super().form_invalid(form)


class EventEnrollView(LoginRequiredMixin, CreateView):
    model = Enroll
    form_class = EventEnrollForm

    def get_success_url(self):
        return self.object.event.get_absolute_url()

    def form_valid(self, form):
        new_enroll = Enroll(
            user=self.request.user,
            event=self.object,
            created=datetime.date.today()

        )
        new_enroll.save()
        messages.success(self.request, f'Запись добавлена')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, 'Вы уже записаны на это событие')
        event = form.cleaned_data.get('event', None)
        redirect_url = event.get_absolute_url() if event else reverse_lazy('events:event_list')
        return HttpResponseRedirect(redirect_url)


class EventUpdateView(LoginRequiredMixin, UpdateView):
    model = Event
    template_name = 'events/event_update.html'
    form_class = EventUpdateForm

    def get_context_data(self, **kwargs):
        event = self.object
        context = super().get_context_data(**kwargs)

        review_users = []
        review_list = event.reviews.all()
        context['review_list'] = review_list.order_by('rate')
        for review in review_list:
            review_users.append(review.user)
        context['review_user_list'] = review_users

        return context

    def form_valid(self, form):
        messages.success(self.request, f'Cобытие {form.cleaned_data["title"]} успешно изменено')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, form.non_field_errors())
        return super().form_invalid(form)


class EventDeleteView(LoginRequiredMixin, DeleteView):
    model = Event
    template_name = 'events/event_update.html'
    success_url = reverse_lazy('events:event_list')

    def delete(self, request, *args, **kwargs):
        result = super().delete(request, *args, **kwargs)
        messages.success(request, f'Событие {self.object} удалено')
        return result


@require_POST
def create_review(request):
    data = {
        'ok': True,
        'msg': '',
        'rate': request.POST.get('rate'),
        'text': request.POST.get('text'),
        'created': datetime.date.today(),
        'user_name': ''
    }

    try:
        event = Event.objects.get(pk=request.POST.get('event_id'))
    except ObjectDoesNotExist:
        data['msg'] = 'Событие не найдено'
        data['ok'] = False
        return JsonResponse(data)

    if not request.user.is_authenticated:
        data['msg'] = 'Отзывы могут оставлять только зарегистрированные пользователи'
        data['ok'] = False
        return JsonResponse(data)

    data['user_name'] = request.user.__str__()

    if Review.objects.filter(user=request.user, event=event).count() != 0:
        data['msg'] = 'Вы уже оставляли отзыв к этому событию'
        data['ok'] = False

    elif data['rate'] == 0 or data['text'] == '':
        data['msg'] = 'Оценка и текст отзыва - обязательные поля'
        data['ok'] = False

    else:
        new_review = Review(
            user=request.user,
            event=event,
            rate=data['rate'],
            text=data['text'],
            created=data['created'],
            updated=data['created']
        )
        new_review.save()

    return JsonResponse(data)

events/templates/events/event_detail.html
{% extends "__base.html" %}
{% load static %}
{% block title %}Событие {{ event.title }}{% endblock %}

{% block content %}
<div class="container-fluid mt-3">
    <div class="row">
        <div class="col-md-12 col-lg-12 col-xl-12">
            <div class="card m-b-30">
                <div class="card-body">
                    <div class="row">
                        <div class="col-lg-6 col-xl-5 mb-4">
                            <img src="{{event.logo_url}}" class="img-fluid" alt="event">
                        </div>
                        <div class="col-lg-6 col-xl-7">
                            {% if event.is_private %}
                                <p data-test="is_private" class="badge bg-dark">Private</p>
                            {% endif %}
                            <h2 data-test="event_title">{{ event.title }}</h2>
                            <p data-test="event_rate" class="badge bg-warning"> {{ event.rate }} / 5</p>
                            <h5 data-test="event_category" class="mt-3">{{ event.category }}</h5>
                            <p data-test="event_description" class="my-4">{{ event.description }}</p>
                            <ul>
                                {% for feature in event.features.all %}
                                    <li data-test="feature">{{feature}}</li>
                                {% endfor %}
                            </ul>
                            <p>
                                дата: <strong>{{ event.date_start|date:"d.m.Y в H:i"}}</strong>
                            </p>
                            <div class="button-list mt-5 mb-5 d-flex">
                                <form action="{% url 'events:event_enroll' %}" method="post" class="me-2">
                                    {% csrf_token %}
                                    {% if places_left != 0 %}
                                        <button data-test="enroll"
                                                type="submit"
                                                class="btn btn-success">
                                            Записаться
                                        </button>
                                    {% else %}
                                        <button data-test="enroll"
                                                type="button"
                                                class="btn btn-success"
                                                disabled=True>
                                            Мест нет
                                        </button>
                                    {% endif %}

                                </form>
                                <a href="{% url 'events:event_update' event.pk %}" class="btn btn-primary me-2">
                                    <i class="bi bi-pencil"></i>Изменить
                                </a>
                                <button type="button" class="btn btn-outline-danger"
                                        title="Добавить в избранное">
                                    <i class="bi bi-heart-fill"></i>
                                </button>
                            </div>
                            <div class="card text-center col-xl-6 m-b-30 bg-info-rgba border btn-shadow">
                                <div class="card-header">
                                    <h5 class="card-title">Количество участников</h5>
                                </div>
                                <div class="card-body">
                                    <i class="bi bi-emoji-smile text-success" style="font-size: 3rem"></i>
                                    <h4 data-test="enroll_count">
                                        {{ event.display_enroll_count }} из {{ event.participants_number }}
                                    </h4>
                                    <p data-test="places_left">
                                    {% if places_left == 0 %}
                                        осталось мест: мест нет
                                    {% else %}
                                        осталось мест: {{ places_left }}
                                    {% endif %}
                                    </p>
                                    <div class="progress" style="height: 5px;">

                                            <div data-test="progressbar"
                                                 class="progress-bar bg-success"
                                                 role="progressbar"
                                                 style="width:{{fullness_percent}}%"
                                                 aria-valuenow="{{fullness_percent}}"
                                                 aria-valuemin="0"
                                                 aria-valuemax="100">
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row mt-4" id="reviews">
        <h2 class="card-title">Отзывы</h2>
        <div class="col-lg-12" id="reviewCol">
            <div class="card my-3 shadow">
                <div class="card-header">
                    <h4 class="card-title">Написать отзыв</h4>
                </div>
                <div class="card-body">
                    <form id="formReview">
                        <div class="d-none">{% csrf_token %}</div>
                        <input type="hidden" name="event_id" value="{{ event.id }}">
                        <div class="row row-cols-lg-auto g-3 mb-3 align-items-start">
                            <div class="col-12">
                                <label for="rate" class="form-label">Оценка</label>
                                <select class="form-select" id="rate" name="rate">
                                    <option value="1">1</option>
                                    <option value="2">2</option>
                                    <option value="3">3</option>
                                    <option value="4">4</option>
                                    <option value="5">5</option>
                                </select>
                            </div>
                        </div>
                        <div class="col-12">
                            <label for="text" class="form-label">Текст отзыва</label>
                            <textarea class="form-control"
                                      name="text" id="text"
                                      rows="3"></textarea>
                        </div>
                        <button type="button" class="btn btn-primary mt-3" id="btnSendReview">
                            Отправить отзыв
                        </button>
                    </form>
                </div>
            </div>
            {% for review in event.reviews.all %}
                <div class="card my-3">
                    <div class="card-header pb-0">
                        <h5 class="card-title">
                            {{ review.user.first_name }} {{ review.user.last_name }}
                            <span class="badge bg-warning">{{ review.rate }}</span>
                        </h5>
                    </div>
                    <div class="card-body">
                        <img src="/static/images/users/men.svg" class="img-fluid me-3" alt="user">
                        <p data-test="review_text" class="mb-0 d-inline">
                            {{ review.text }}
                        </p>
                        <p data-test="review_date" class="mt-3">{{ review.created|date:"d.m.Y" }}</p>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</div>

<script>
    function addNewReview(innerText = '', innerHTML = '') {
        let reviewHTML = innerHTML
        if (!reviewHTML) {
            reviewHTML = `
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            ` + innerText.toString().replaceAll('\n', '<br>') + `
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>`
        }
        let container = document.getElementById('reviewCol'),
            firstChild = container.childNodes[1]
        if (container && firstChild) {
            let newReview = document.createElement('div')
            newReview.innerHTML = reviewHTML
            firstChild.parentNode.insertBefore(newReview, firstChild.nextSibling)
        }
    }

    function createNewReview(data) {
        let rate = '',
            text = '',
            created = '',
            user_name = '',
            ok = false,
            msg = ''
        try {
            ok = data.ok
            msg = data.msg
            rate = data.rate
            text = data.text
            created = data.created
            user_name = data.user_name
        } catch (err) {
            addNewReview(err)
        }
        if (ok === true) {
            if (!rate || !text || !created) {
                let errMsg = 'rate = ' + rate + '\ntext = ' + text + '\ncreated = ' + created
                addNewReview('Некоторые переменные в JsonResponse не определены:\n' + errMsg)
            } else {
                let newReviewInnerHTML = `
                    <div class="card my-3">
                        <div class="card-header pb-0">
                            <h5 class="card-title">
                                ` + user_name + `
                                <span class="badge bg-warning">` + rate + `</span>
                            </h5>
                        </div>
                        <div class="card-body">
                            <img src="{% static 'images/users/men.svg' %}" class="img-fluid me-3" alt="user">
                            <p data-test="review_text" class="mb-0 d-inline">
                                ` + text + `
                            </p>
                            <p data-test="review_date" class="mt-3">` + created + `</p>
                        </div>
                    </div>`
                addNewReview('', newReviewInnerHTML)
            }
        } else {
            let extraMsg = ''
            if (ok === false) {
                extraMsg = msg
            } else {
                extraMsg = 'Новый отзыв не отображен, потому что в ответе от сервера не найден ключ "ok"'
                if (msg) {
                    extraMsg = extraMsg + '\nСообщение от сервера: ' + msg
                }
            }
            addNewReview(extraMsg)
        }
    }

    function ready() {
        let formReview = document.getElementById('formReview')
        let btnSendReview = document.getElementById('btnSendReview')
        if (formReview && btnSendReview) {
            btnSendReview.onclick = () => {
                // Создаем JavaScript объект formData - в этом объекте хранятся данные для HTTP запроса
                // Это данные из формы добавления отзыва - поля Оценка и Текст отзыва
                let formData = new FormData(formReview)
                // Создаем JavaScript объект для отправки HTTP запроса
                let xhr = new XMLHttpRequest()
                // Отправляем запрос с методом POST на нужный URL адрес
                xhr.open("POST", "{% url 'api_events:create_review' %}")
                // Добавляем в запрос данные с формы отзыва
                xhr.send(formData)
                // Ждем ответа от сервера. Метод onloadend срабатывает когда придет ответ
                xhr.onloadend = function () {
                    // Если статус ответа = 200, значит все OK. Отправленный HTTP успешно вернул ответ
                    if (xhr.status === 200) {
                        try {
                            // Строка формата JSON содержится в реквизите xhr.response - парсим ее
                            let response = JSON.parse(xhr.response)
                            // Запускаем функцию по созданию на странице нового элемента с отзывом
                            createNewReview(response)
                        } catch (err) {
                            // Если не удалось распарсить строку ответа, то выводим ошибку
                            console.error(err)
                            addNewReview(err)
                        }
                    } else {
                        // Если статус ответа не 200, значит при обработке HTTP возникли какие-то ошибки
                        // Ситуации могут быть разные. Выводим ошибку со статусом ответа
                        addNewReview("Ошибка " + xhr.status)
                    }
                }
            }
        }
    }

    document.addEventListener("DOMContentLoaded", ready)
</script>
{% endblock %}

events/templates/events/event_list.html
{% extends "__base.html" %}
{% load static %}
{% block title %}Real World Django - События{% endblock %}

{% block content %}
<div class="container-fluid mt-3">
    <div class="row mb-4">
        <div class="col">
            <div class="card shadow">
                <div class="card-body">
                    <form>
                        <div class="row row-cols-lg-auto g-3 align-items-start">
                            <div class="col-12">
                                <label for="category" class="form-label">Категория:</label>
                                <select class="form-select" id="category">
                                    <option selected="">....................</option>
                                    <option value="1">Спортивный турнир</option>
                                    <option value="2">Семейное мероприятие</option>
                                    <option value="3">Субботник</option>
                                    <option value="4">Волонтерство</option>
                                    <option value="5">Night Party</option>
                                    <option value="6">Дилоги со звездой</option>
                                </select>
                            </div>
                            <div class="col-12">
                                <label for="features" class="form-label">Свойства:</label>
                                <select class="form-select" multiple="" id="features">
                                    <option value="1">На открытом воздухе</option>
                                    <option value="2">Приглашенная знаменитость</option>
                                    <option value="3">Живая музыка</option>
                                    <option value="4">Песни у костра</option>
                                    <option value="5">Подарки участникам</option>
                                    <option value="6"> Вечерние танцы</option>
                                </select>
                            </div>
                            <div class="col-12 d-md-flex">
                                <div class="mx-1">
                                    <label for="id_date_start" class="form-label">Дата начала</label>
                                    <input type="date" class="form-control" id="id_date_start">
                                </div>
                                <div class="mx-1">
                                    <label for="id_date_end" class="form-label">Дата окончания</label>
                                    <input type="date" class="form-control" id="id_date_end">
                                </div>
                            </div>
                        </div>
                        <div class="row mt-3">
                            <div class="col-12 d-md-flex">
                                <div class="form-check me-3">
                                    <input class="form-check-input" type="checkbox" value="" id="is_private">
                                    <label class="form-check-label" for="is_private">
                                        Private
                                    </label>
                                </div>
                                <div class="form-check">
                                    <input class="form-check-input" type="checkbox" value="" id="is_available">
                                    <label class="form-check-label" for="is_available">
                                        Есть места
                                    </label>
                                </div>
                            </div>
                            <div class="col-12 mt-3">
                                <button type="submit" class="btn btn-primary">Фильтровать</button>
                                <button type="submit" class="btn btn-outline-danger">Сбросить</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    {% include "snippets/_pagination.html" %}
    <div class="row row-cols-1 row-cols-md-2 row-cols-xl-3 row-cols-xxl-4 g-4">
        {% for event in event_list %}
            <div class="col">
                <div class="card h-100">
                    <div class="card-header">
                        <h5 class="card-title mb-0">{{ event.title }}</h5>
                        {% if event.is_private %}
                            <span data-test="is_private" class="badge bg-dark">Private</span>
                        {% endif %}
                    </div>
                    <div class="card-body">
                        <h3>{{ event.enrolls.count }} из {{ event.participants_number }}</h3>
                        <p>участников</p>
                        <ul class="py-2">
                            {% for feature in event.features.all %}
                                <li>{{ feature }}</li>
                            {% endfor %}
                        </ul>
                        <p>
                            дата: <strong data-test="date_start">{{ event.date_start|date:"d.m.Y в H:i" }}
                        </strong>
                        </p>
                    </div>
                    <div class="card-footer">
                        <a href="{{ event.get_absolute_url }}" class="btn btn-success">Смотреть</a>
                        <a href="{% url 'events:event_update' event.pk %}" class="btn btn-outline-primary" title="Изменить">
                            <i class="bi bi-pencil-square"></i>Изменить
                        </a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}