events/urls.py
from django.urls import path
from . import views
from django.views.decorators.http import require_POST


app_name = 'events'

urlpatterns = [
    path('list/', views.EventListView.as_view(), name='event_list'),
    path('detail/<int:pk>/', views.EventDetailView.as_view(), name='event_detail'),

    path('event-create/', views.EventCreateView.as_view(), name='event_create'),
    path('event-update/<int:pk>/', views.EventUpdateView.as_view(), name='event_update'),
    path('event-enroll/', require_POST(views.EventEnrollView.as_view()), name='event_enroll'),
    path('event-delete/<int:pk>/', views.EventDeleteView.as_view(), name='event_delete'),
]

realworlddjango/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]


if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Backend URLs
urlpatterns += [
    path('events/', include('events.urls'))
]

# API URLs
urlpatterns += [
    path('api/events/', include('events.urls_api')),
]

templates/snippets/_footer.html
<div style="height: 70px"></div>
<div class="footerbar">
    <footer class="footer">
        <p class="mb-0">© Pumpskill. Real World Django</p>
    </footer>
</div>

templates/snippets/_left_menu.html
{% load static %}
<!-- Start LEFT_MENU -->
<div class="leftbar">
    <div class="logobar">
        <a href="index.html" class="logo logo-large">
            <img src="{% static 'images/svg-icon/logo.svg' %}" alt="logo" style="height: 40px">
        </a>
    </div>
    <ul class="vertical-menu" id="vertical-menu">
        <li class="vertical-menu-item">
            <span>Главное</span>
            <ul class="vertical-submenu">
                <li><a href="{% url 'events:event_list' %}">События</a></li>
                <li><a href="mail.html">Подписчики</a></li>
            </ul>
        </li>
        <li class="vertical-menu-item">
            <span>Аккаунт</span>
            <ul class="vertical-submenu">
                <li><a href="profile.html">Мой аккаунт</a></li>
                <li><a href="#">Изменить пароль</a></li>
                <li><a href="#">Сбросить пароль</a></li>
            </ul>
        </li>
    </ul>
</div>
<!-- menu for mobile -->
<div class="topbar-mobile">
    <div class="row align-items-center">
        <div class="col-md-12">
            <div class="mobile-logobar" style="max-width: 40px">
                <a href="#" class="mobile-logo">
                    <img src="{% static 'images/svg-icon/logo.svg' %}" class="img-fluid" alt="logo">
                </a>
            </div>
            <div class="mobile-togglebar">
                <ul class="list-inline mb-0">
                    <li class="list-inline-item">
                        <div class="menubar">
                            <a class="menu-hamburger" href="#" id="menu-hamburger">
                                <img src="{% static 'images/svg-icon/collapse.svg' %}"
                                     class="img-fluid menu-hamburger-collapse"
                                     alt="collapse">
                                <img src="{% static 'images/svg-icon/close.svg' %}"
                                     class="img-fluid menu-hamburger-close"
                                     alt="close">
                            </a>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
<div class="d-md-none" style="height: 90px"></div>
<!-- End LEFT_MENU -->

templates/snippets/_messages.html
{% if messages %}
<div class="container">
    <div class="row">
        <div class="col">
            {% for message in messages %}
            <div class="alert {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
            alert-danger
            {% elif message.level == DEFAULT_MESSAGE_LEVELS.WARNING %}
            alert-warning
            {% elif message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
            alert-success
            {% else %}
            alert-primary
            {% endif %} alert-dismissible fade show" role="alert">
                <p class="my-0 py-0">{{ message }}</p>
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endif %}

templates/snippets/_pagination.html
{% if is_paginated %}
<ul class="pagination">
    <li class="page-item"><a class="page-link" href="?page=1" data-test="p_start">&laquo;</a></li>
    {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}" data-test="p_previous">Previous</a></li>
    {% endif %}
    {% for i in paginator.page_range %}
    <li class="page-item {% if page_obj.number == i %}active{% endif %}">
        <a class="page-link" href="?page={{ i }}">{{ i }}</a>
    </li>
    {% endfor %}
    {% if page_obj.has_next %}
    <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}" data-test="p_next">Next</a></li>
    {% endif %}
    <li class="page-item"><a class="page-link" href="?page={{ paginator.num_pages }}" data-test="p_end">&raquo;</a></li>
</ul>
{% endif %}

templates/snippets/_top_bar.html
 <!-- Start TOP_BAR -->
    <div class="container-fluid bg-white py-3">
        <div class="row align-items-center justify-content-between">
            <div class="col-auto text-center ms-4">
                {% if event %}
                    <h4>Событие</h4>
                {% else %}
                    <h4>События</h4>
                {% endif %}
            </div>
            <div class="col-auto text-center me-4">
                {% if user.is_authenticated %}
                    <a href="{% url 'events:event_create' %}" class="btn btn-outline-primary">+ Добавить событие</a>
                {% else %}
                    <a href="#" class="btn btn-outline-primary">Войти</a>
                    <a href="#" class="btn btn-primary">Регистрация</a>
                {% endif %}
            </div>
        </div>
    </div>
    <!-- End TOP_BAR -->